name: RITBuddy CD

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # ðŸ”§ Backend image (tag: backend)
    - name: Build and Push Backend Docker Image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: tanushree0411/blog_repo
        tags: backend
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        context: ./backend
        dockerfile: ./backend/Dockerfile

    # ðŸ”§ Frontend image (tag: frontend)
    - name: Build and Push Frontend Docker Image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: tanushree0411/blog_repo
        tags: frontend
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        context: ./frontend
        dockerfile: ./my-app/Dockerfile